spring:
  application:
    name: calculator
server:
  port: 8080
  servlet:
    context-path: /geo-calculator
springdoc: #https://springdoc.org/properties.html
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none #?? operation ?? ??? ???
    display-operation-id: true
    filter: true